# Site settings
ref: CSCD27
title: Computer and Network Security
edition: Fall 2019
description: This course is meant to offer Computer Science undergraduate students a broad overview of the field of computer security. Students will learn the basic concepts in computer security including software vulnerability analysis and defense, networking security, applied cryptography. Students will also learn the fundamental methodology for how to design and analyze the security of critical systems.
website: https://thierrysans.me/CSCD27/
github: https://github.com/ThierrySans/CSCD27
piazza: https://piazza.com/mail.utoronto.ca/fall2019/cscd27
feedback: https://forms.gle/GiDcKNfKw9vv1vFs9

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: TBD
  location: IC-346
  contact: Piazza only (no mail)
  hours: Thursday 9-11am

assistants:
    # - name: Xuan Wei
    #   role:  T01 & P04
    #   contact: x.wei@mail.utoronto.ca
    #   hours: Fri 11-11:30am
    #   location: IC-400

  
timings:
    - section: LEC01 
      time: Thursday 11:00-13:00
      location: SW 143
    - section: PRA01
      time: Monday 13:00-14:00
      location: BV 473        
    - section: PRA02
      time: Tuesday 14:00-15:00
      location: BV 473        
    - section: PRA03
      time: Tuesday 10:00-11:00
      location: BV 473        
    - section: PRA04
      time: Tuesday 16:00-17:00
      location: BV 473
    - section: TUT01
      time: Tuesday 17:00-18:00
      location: AA 207        
    - section: TUT02
      time: Thursday 11:00-12:00
      location: IC 120        
    - section: TUT03
      time: Tuesday 9:00-10:00
      location: MW 140     
    - section: TUT04
      time: Monday 12:00-13:00
      location: IC 302    
        
        
first: 20190905